apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: "itzg/minecraft-server:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "VANILLA"
            - name: VERSION
              value: "LATEST"
            - name: DIFFICULTY
              value: "easy"
            - name: WHITELIST
              value: ""
            - name: OPS
              value: "durandom,GNU_4K"
            - name: ICON
              value: ""
            - name: MAX_PLAYERS
              value: "20"
            - name: MAX_WORLD_SIZE
              value: "10000"
            - name: ALLOW_NETHER
              value: "true"
            - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
              value: "true"
            - name: ENABLE_COMMAND_BLOCK
              value: "true"
            - name: FORCE_GAMEMODE
              value: "false"
            - name: GENERATE_STRUCTURES
              value: "true"
            - name: HARDCORE
              value: "false"
            - name: MAX_BUILD_HEIGHT
              value: "256"
            - name: MAX_TICK_TIME
              value: "60000"
            - name: SPAWN_ANIMALS
              value: "true"
            - name: SPAWN_MONSTERS
              value: "true"
            - name: SPAWN_NPCS
              value: "true"
            - name: VIEW_DISTANCE
              value: "10"
            - name: SEED
              value: ""
            - name: MODE
              value: "survival"
            - name: MOTD
              value: "B4mad Minecraft on Operate First!"
            - name: PVP
              value: "true"
            - name: LEVEL_TYPE
              value: "DEFAULT"
            - name: GENERATOR_SETTINGS
              value: ""
            - name: LEVEL
              value: "world"
            - name: ONLINE_MODE
              value: "true"
            - name: MEMORY
              value: "1024M"
            - name: JVM_OPTS
              value: ""
            - name: JVM_XX_OPTS
              value: ""
            - name: ENABLE_RCON
              value: "false"

          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: datadir
              mountPath: /data
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: minecraft-server-datadir
